### ISSUE TITLE
some preliminary issues

### ISSUE THREAD

**Issue by riocrokite** [BobPalmer/Regolith#2]
As always great work RoverDude!

After some testing couple of small things:

- scanner indications sometimes inconsistent with resources that could be mined; for example composition shows both argon and xeon and sometimes there is no xeon, sometimes no argon. other example, sometimes karborundum is on scanner but is not on asteroid. scanner readouts were taken after attaching to an asteroid. pic: karborundum on scanner, however not in cargo (after mining)
![issue](https://cloud.githubusercontent.com/assets/9766897/5057701/b3040ab6-6cd0-11e4-83e9-aaa4bc8770f8.png)

- animations of mining equipment last if i rectract them (without stopping first)

- venting rock sometimes fail (i.e. i have 3228 rock and i can vent it till 3000 and then it won't go down from that point

**Comment by BobPalmer** [comment]
Closing as this should be over on the AMT or ART repo.
