### ISSUE TITLE
GetAbundance Arguments

### ISSUE THREAD

**Issue by DMagic1** [BobPalmer/Regolith#24]
Should the HarvestType be cast internally from an int for [GetAbundance](https://github.com/BobPalmer/Regolith/blob/master/Regolith/Regolith/Planetary/RegolithResourceMap.cs#L78)?

    public static float GetAbundance(double latitude, double longitude, string resourceName, int bodyId,
            HarvestTypes resourceType = HarvestTypes.Planetary, double altitude = 0)

Reflection methods don't play nice with default parameters like this. It's probably possible to create a delegate that assigns those values to their defaults, but it's a lot more trouble than just using generic types.

**Comment by BobPalmer** [comment]
Just changed it up to keep it to the original four you use.

Question for you:  Biome unlocking is now in.  Which means a -1 is returned until that biome is explored.  What are your thoughts RE SCANSat?   As it stands, it's defaulting to opt in.  I can slap in a default parm for you, unless you have a strong opinion one way or the other (FYI it's retroactive so if you scan then unlock, the map would light up)

**Comment by DMagic1** [comment]
Thanks. But SCANsat is still defining all six parameters, (double, double, string, int, int, double), any change to that will break the reflection method. That's why I recommend just internally casting the int to a HarvestType. Then again, I am about to release a new update for SCANsat, version 10, doing away with the dev build/stable build problem, so cutting off the last two parameters would be fine too.

It would make sense to have the different scanner types give consistent results. Sending -1 works fine for SCANsat, it just records any value below a certain cutoff as 0, so I wouldn't need to change anything to accommodate that, and everything would update fine when the biome unlocks.

**Comment by BobPalmer** [comment]
Ok so I will swap back in the legacy method just in case you want to make an atmospheric scanner down the road (esp given that atmospheres can also have variance).

Last thought - I wonder if there's a way to visually show in SCANSat that you have a -1 for that biome - would make unlocking really easy.

I'll push a new release tomorrow (late here).

**Comment by BobPalmer** [comment]
For clarity - I will re-add the old six parameters

**Comment by DMagic1** [comment]
Hmm... You could add a seventh parameter, maybe just a bool, to enable toggling of the biome check. That way I could define the biome check state in the SCANsat resource definition configs and people could turn it off if they want to (or maybe put a toggle in the settings menu). I'm pretty sure that I'm going to update tomorrow or Thursday, so this wouldn't really be a problem to break compatibility with the old versions.

Some kind of different visual indicator for scanned-but-not-unlocked would probably be a good idea too, that's something I can add in later.

**Comment by BobPalmer** [comment]
Let's go with the seventh parameter then.  I'll add it into that method you currently use and have an update today.

**Comment by BobPalmer** [comment]
Closing as this will be buttoned up in the next release.
