### ISSUE TITLE
Min abundance needs tweak

### ISSUE THREAD

**Issue by DMagic1** [BobPalmer/Regolith#25]
[This min abundance value](https://github.com/BobPalmer/Regolith/blob/master/Regolith/Regolith/Planetary/RegolithResourceMap.cs#L186) has been multiplied by 1000 a few lines up:

      var minAbundance = Math.Max(0.01f,min/100f);

So the min abundance is being reported as 10X what it should be, ie 1000% for Karbonite on Kerbin

Otherwise SCANsat seems good for this update.

**Comment by BobPalmer** [comment]
Fixed
