### ISSUE TITLE
ISRU H2O->LFO preservation of mass

### ISSUE THREAD

**Issue by Donziboy2** [BobPalmer/Regolith#5]
Just looking at the ISRU, I noticed the mass of my craft was going up pretty fast when converting water to LFO.
At present it converts 2 units of water into 0.9 units Liquid Fuel and 1.1 units Oxidizer.  This would be all well and good if both had the same mass.
Water is 1kg per unit, Liquid Fuel is 5kg per unit and Oxidizer is 5kg per unit.  So basically you take 2kg and make 10kg :) 

Current code.
[CODE]
MODULE
{
	name = REGO_ModuleResourceConverter
	StartActionName = Start H2O->LFO 
	StopActionName = Stop H2O->LFO
	RecipeInputs = ElectricCharge,10,Water,2
	RecipeOutputs = LiquidFuel,0.9,false,Oxidizer,1.1,false
[/CODE]

Proposed change for conservation of mass.
[CODE]
MODULE
{
	name = REGO_ModuleResourceConverter
	StartActionName = Start H2O->LFO 
	StopActionName = Stop H2O->LFO
	RecipeInputs = ElectricCharge,10,Water,2
	RecipeOutputs = LiquidFuel,0.18,false,Oxidizer,0.22,false
[/CODE]

**Comment by BobPalmer** [comment]
Closing as this is an AMT issue
